/**
 * OralEye API
 * API for controlling lights and camera on OralEye device
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OralEyeApi);
  }
}(this, function(expect, OralEyeApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OralEyeApi.LightsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LightsApi', function() {
    describe('lightsBlueMaxTimePost', function() {
      it('should call lightsBlueMaxTimePost successfully', function(done) {
        //uncomment below and update the code to test lightsBlueMaxTimePost
        //instance.lightsBlueMaxTimePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('lightsControlPost', function() {
      it('should call lightsControlPost successfully', function(done) {
        //uncomment below and update the code to test lightsControlPost
        //instance.lightsControlPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('lightsStatusGet', function() {
      it('should call lightsStatusGet successfully', function(done) {
        //uncomment below and update the code to test lightsStatusGet
        //instance.lightsStatusGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
