/**
 * OralEye API
 * API for controlling lights and camera on OralEye device
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CameraManualFocusPostRequest model module.
 * @module model/CameraManualFocusPostRequest
 * @version 0.0.1
 */
class CameraManualFocusPostRequest {
    /**
     * Constructs a new <code>CameraManualFocusPostRequest</code>.
     * @alias module:model/CameraManualFocusPostRequest
     */
    constructor() { 
        
        CameraManualFocusPostRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CameraManualFocusPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CameraManualFocusPostRequest} obj Optional instance to populate.
     * @return {module:model/CameraManualFocusPostRequest} The populated <code>CameraManualFocusPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CameraManualFocusPostRequest();

            if (data.hasOwnProperty('distance')) {
                obj['distance'] = ApiClient.convertToType(data['distance'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CameraManualFocusPostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CameraManualFocusPostRequest</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Focus distance in millimeters
 * @member {Number} distance
 */
CameraManualFocusPostRequest.prototype['distance'] = undefined;






export default CameraManualFocusPostRequest;

