/**
 * OralEye API
 * API for controlling lights and camera on OralEye device
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LightsBlueMaxTimePostRequest model module.
 * @module model/LightsBlueMaxTimePostRequest
 * @version 0.0.1
 */
class LightsBlueMaxTimePostRequest {
    /**
     * Constructs a new <code>LightsBlueMaxTimePostRequest</code>.
     * @alias module:model/LightsBlueMaxTimePostRequest
     */
    constructor() { 
        
        LightsBlueMaxTimePostRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LightsBlueMaxTimePostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LightsBlueMaxTimePostRequest} obj Optional instance to populate.
     * @return {module:model/LightsBlueMaxTimePostRequest} The populated <code>LightsBlueMaxTimePostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LightsBlueMaxTimePostRequest();

            if (data.hasOwnProperty('max_time')) {
                obj['max_time'] = ApiClient.convertToType(data['max_time'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LightsBlueMaxTimePostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LightsBlueMaxTimePostRequest</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Maximum time in seconds the blue light can stay on
 * @member {Number} max_time
 */
LightsBlueMaxTimePostRequest.prototype['max_time'] = undefined;






export default LightsBlueMaxTimePostRequest;

